# Copyright (C) 2002-2023 CERN for the benefit of the ATLAS collaboration

AntiKt4UFOCSSKLowPtJetsCPContent = [
"AntiKt4UFOCSSKLowPtJets",
"AntiKt4UFOCSSKLowPtJetsAux.JetConstitScaleMomentum_pt.JetConstitScaleMomentum_eta.JetConstitScaleMomentum_phi.JetConstitScaleMomentum_m",
"AntiKt4UFOCSSKLowPtJetsAux.ActiveArea4vec_eta.ActiveArea4vec_m.ActiveArea4vec_phi.ActiveArea4vec_pt.DetectorEta.DetectorY",
"AntiKt4UFOCSSKLowPtJetsAux.NumTrkPt500.SumPtTrkPt500.NumChargedPFOPt500.SumPtChargedPFOPt500.NumTrkPt1000.NumChargedPFOPt1000.TrackWidthPt1000.ChargedPFOWidthPt1000",
"AntiKt4UFOCSSKLowPtJetsAux.GhostTrack.Jvt.JVFCorr.JvtRpt.GhostMuonSegmentCount.DFCommonJets_fJvt",
"AntiKt4UFOCSSKLowPtJetsAux.NNJvt.NNJvtRpt.NNJvtPass",
"AntiKt4UFOCSSKLowPtJetsAux.EnergyPerSampling.FracSamplingMax.FracSamplingMaxIndex.Timing.N90Constituents",
"AntiKt4UFOCSSKLowPtJetsAux.PartonTruthLabelID.ConeTruthLabelID.HadronConeExclExtendedTruthLabelID.HadronConeExclTruthLabelID",
"PrimaryVertices",
"PrimaryVerticesAux.vertexType" 
]
