# Copyright (C) 2002-2023 CERN for the benefit of the ATLAS collaboration

AntiKt4EMPFlowByVertexJetsCPContent = [
"Kt4EMPFlowEventShape",
"Kt4EMPFlowEventShapeAux.Density",
"Kt4EMPFlowPUSBEventShape",
"Kt4EMPFlowPUSBEventShapeAux.Density",
"Kt4EMPFlowNeutEventShape",
"Kt4EMPFlowNeutEventShapeAux.Density",
"AntiKt4EMPFlowByVertexJetsCPContent",
"AntiKt4EMPFlowByVertexJetsCPContentAux.JetConstitScaleMomentum_pt.JetConstitScaleMomentum_eta.JetConstitScaleMomentum_phi.JetConstitScaleMomentum_m",
"AntiKt4EMPFlowByVertexJetsCPContentAux.ActiveArea4vec_eta.ActiveArea4vec_m.ActiveArea4vec_phi.ActiveArea4vec_pt.DetectorEta.DetectorY",
"AntiKt4EMPFlowByVertexJetsCPContentAux.NumTrkPt500.SumPtTrkPt500.NumChargedPFOPt500.SumPtChargedPFOPt500.NumTrkPt1000.NumChargedPFOPt1000.TrackWidthPt1000.ChargedPFOWidthPt1000",
"AntiKt4EMPFlowByVertexJetsCPContentAux.GhostTrack.Jvt.JVFCorr.JvtRpt.GhostMuonSegmentCount.DFCommonJets_fJvt",
"AntiKt4EMPFlowByVertexJetsCPContentAux.NNJvt.NNJvtRpt.NNJvtPass",
"AntiKt4EMPFlowByVertexJetsCPContentAux.EnergyPerSampling.FracSamplingMax.FracSamplingMaxIndex.Timing.N90Constituents",
"AntiKt4EMPFlowByVertexJetsCPContentAux.PartonTruthLabelID.ConeTruthLabelID.HadronConeExclExtendedTruthLabelID.HadronConeExclTruthLabelID",
"AntiKt4EMPFlowByVertexJetsCPContentAux.OriginVertex",
"PrimaryVertices",
"PrimaryVerticesAux.vertexType" 
]
