# Copyright (C) 2002-2021 CERN for the benefit of the ATLAS collaboration

JetTriggerContentRun3 = [
"HLT_AntiKt4EMTopoJets_nojcalib",       
"HLT_AntiKt4EMTopoJets_nojcalibAux.m.pt.eta.phi.ActiveArea.ActiveArea4vec_m.ActiveArea4vec_pt.ActiveArea4vec_eta.ActiveArea4vec_phi.EMFrac.HECFrac.DetectorEta.DetectorPhi.NumTrkPt1000.TrackWidthPt1000.SumPtTrkPt500.EnergyPerSampling.SumPtChargedPFOPt500.JVFCorr.JetConstitScaleMomentum_m.JetConstitScaleMomentum_pt.JetConstitScaleMomentum_eta.JetConstitScaleMomentum_phi",
"HLT_AntiKt4EMTopoJets_nojcalib_ftf",
"HLT_AntiKt4EMTopoJets_nojcalib_ftfAux.m.pt.eta.phi.ActiveArea.ActiveArea4vec_m.ActiveArea4vec_pt.ActiveArea4vec_eta.ActiveArea4vec_phi.EMFrac.HECFrac.DetectorEta.DetectorPhi.NumTrkPt1000.TrackWidthPt1000.SumPtTrkPt500.EnergyPerSampling.JVFCorr.JetConstitScaleMomentum_m.JetConstitScaleMomentum_pt.JetConstitScaleMomentum_eta.JetConstitScaleMomentum_phi",
"HLT_AntiKt4EMTopoJets_subjesIS",
"HLT_AntiKt4EMTopoJets_subjesISAux.m.pt.eta.phi.Timing.JetPileupScaleMomentum_m.JetPileupScaleMomentum_pt.JetPileupScaleMomentum_eta.JetPileupScaleMomentum_phi.JetEtaJESScaleMomentum_m.JetEtaJESScaleMomentum_pt.JetEtaJESScaleMomentum_eta.JetEtaJESScaleMomentum_phi.JetGSCScaleMomentum_m.JetGSCScaleMomentum_pt.JetGSCScaleMomentum_eta.JetGSCScaleMomentum_phi",
"HLT_AntiKt4EMTopoJets_subresjesgscIS_ftf",
"HLT_AntiKt4EMTopoJets_subresjesgscIS_ftfAux.m.pt.eta.phi.Jvt.JvtRpt.Timing.JetPileupScaleMomentum_m.JetPileupScaleMomentum_pt.JetPileupScaleMomentum_eta.JetPileupScaleMomentum_phi.JetEtaJESScaleMomentum_m.JetEtaJESScaleMomentum_pt.JetEtaJESScaleMomentum_eta.JetEtaJESScaleMomentum_phi.JetGSCScaleMomentum_m.JetGSCScaleMomentum_pt.JetGSCScaleMomentum_eta.JetGSCScaleMomentum_phi",
"HLT_AntiKt4EMPFlowJets_nojcalib_ftf",
"HLT_AntiKt4EMPFlowJets_nojcalib_ftfAux.m.pt.eta.phi.ActiveArea.ActiveArea4vec_m.ActiveArea4vec_pt.ActiveArea4vec_eta.ActiveArea4vec_phi.EMFrac.HECFrac.DetectorEta.DetectorPhi.NumTrkPt1000.TrackWidthPt1000.SumPtTrkPt500.EnergyPerSampling.SumPtChargedPFOPt500.JVFCorr.JetConstitScaleMomentum_m.JetConstitScaleMomentum_pt.JetConstitScaleMomentum_eta.JetConstitScaleMomentum_phi",
"HLT_AntiKt4EMPFlowJets_subresjesgscIS_ftf",
"HLT_AntiKt4EMPFlowJets_subresjesgscIS_ftfAux.m.pt.eta.phi.Jvt.JvtRpt.Timing.dips20211116_pb.dips20211116_pu.dips20211116_pc.fastDIPS20211215_pb.fastDIPS20211215_pu.fastDIPS20211215_pc.JetPileupScaleMomentum_m.JetPileupScaleMomentum_pt.JetPileupScaleMomentum_eta.JetPileupScaleMomentum_phi.JetEtaJESScaleMomentum_m.JetEtaJESScaleMomentum_pt.JetEtaJESScaleMomentum_eta.JetEtaJESScaleMomentum_phi.JetGSCScaleMomentum_m.JetGSCScaleMomentum_pt.JetGSCScaleMomentum_eta.JetGSCScaleMomentum_phi",
"HLT_AntiKt10EMPFlowCSSKSoftDropBeta100Zcut10Jets_jes_ftf",
"HLT_AntiKt10EMPFlowCSSKSoftDropBeta100Zcut10Jets_jes_ftfAux.JetConstitScaleMomentum_pt.JetConstitScaleMomentum_eta.JetConstitScaleMomentum_phi.JetConstitScaleMomentum_m.JetEtaJESScaleMomentum_pt.JetEtaJESScaleMomentum_eta.JetEtaJESScaleMomentum_phi.JetEtaJESScaleMomentum_m",
"HLT_AntiKt10LCTopoTrimmedPtFrac4SmallR20Jets_jes",
"HLT_AntiKt10LCTopoTrimmedPtFrac4SmallR20Jets_jesAux.JetConstitScaleMomentum_pt.JetConstitScaleMomentum_eta.JetConstitScaleMomentum_phi.JetConstitScaleMomentum_m.JetEtaJESScaleMomentum_pt.JetEtaJESScaleMomentum_eta.JetEtaJESScaleMomentum_phi.JetEtaJESScaleMomentum_m"]
