# Copyright (C) 2002-2023 CERN for the benefit of the ATLAS collaboration

ElectronsCPContent = [
"Electrons",
"ElectronsAux.trackParticleLinks.pt.eta.phi.m.charge.author.OQ.DFCommonElectronsLHVeryLoose.DFCommonElectronsLHLoose.DFCommonElectronsLHLooseBL.DFCommonElectronsLHMedium.DFCommonElectronsLHTight.DFCommonElectronsLHVeryLooseIsEMValue.DFCommonElectronsLHLooseIsEMValue.DFCommonElectronsLHLooseBLIsEMValue.DFCommonElectronsLHMediumIsEMValue.DFCommonElectronsLHTightIsEMValue.DFCommonElectronsDNNLoose.DFCommonElectronsDNNLooseIsEMValue.DFCommonElectronsDNNMedium.DFCommonElectronsDNNMediumIsEMValue.DFCommonElectronsDNNTight.DFCommonElectronsDNNTightIsEMValue.DFCommonElectronsDNN_pel.DFCommonElectronsDNN_pcf.DFCommonElectronsDNN_ppc.DFCommonElectronsDNN_phf.DFCommonElectronsDNN_ple.DFCommonElectronsDNN_plh.ptvarcone20.topoetcone20.topoetcone20ptCorrection.ptcone20_Nonprompt_All_MaxWeightTTVALooseCone_pt500.ptcone20_Nonprompt_All_MaxWeightTTVALooseCone_pt1000.ptvarcone30_Nonprompt_All_MaxWeightTTVALooseCone_pt500.ptvarcone30_Nonprompt_All_MaxWeightTTVALooseCone_pt1000.neflowisol20.core57cellsEnergyCorrection.topoetconecoreConeEnergyCorrection.DFCommonCrackVetoCleaning.caloClusterLinks.ambiguityLink.truthParticleLink.truthOrigin.truthType.truthPdgId.firstEgMotherTruthType.firstEgMotherTruthOrigin.firstEgMotherTruthParticleLink.firstEgMotherPdgId.ambiguityType.DFCommonAddAmbiguity",
"GSFTrackParticles",
"GSFTrackParticlesAux.chiSquared.phi.d0.theta.qOverP.definingParametersCovMatrixDiag.definingParametersCovMatrixOffDiag.numberOfPixelHits.numberOfPixelOutliers.numberOfPixelDeadSensors.numberOfSCTHits.numberOfSCTOutliers.numberOfSCTDeadSensors.z0.vz.charge.vertexLink.numberOfInnermostPixelLayerHits.numberOfInnermostPixelLayerOutliers.numberOfNextToInnermostPixelLayerOutliers.expectInnermostPixelLayerHit.truthParticleLink.originalTrackParticle.numberOfNextToInnermostPixelLayerHits.expectNextToInnermostPixelLayerHit",
"GSFConversionVertices",
"GSFConversionVerticesAux.px.py.pz",
"PrimaryVertices",
"PrimaryVerticesAux.trackParticleLinks.vertexType.neutralParticleLinks",
"egammaClusters",
"egammaClustersAux.calE.calEta.calPhi.e_sampl.eta_sampl.ETACALOFRAME.PHICALOFRAME.ETA2CALOFRAME.PHI2CALOFRAME.constituentClusterLinks",
"TopoClusterIsoCentralEventShape",
"TopoClusterIsoCentralEventShapeAux.Density",
"TopoClusterIsoForwardEventShape",
"TopoClusterIsoForwardEventShapeAux.Density",
"NeutralParticleFlowIsoCentralEventShape",
"NeutralParticleFlowIsoCentralEventShapeAux.Density",
"NeutralParticleFlowIsoForwardEventShape",
"NeutralParticleFlowIsoForwardEventShapeAux.Density",
]

from AthenaConfiguration.AllConfigFlags import initConfigFlags
flags = initConfigFlags()
if flags.Derivation.Egamma.addECIDS:
    ElectronsCPContent.extend(["ElectronsAux.DFCommonElectronsECIDS.DFCommonElectronsECIDSResult"])
